// Plan semanal. m = g/ml de María, c = de Carlos, u = unidad ('g' por defecto), note opcional.
// El `id` de cada ingrediente se añade en catalog.js (slug del nombre).
export const DAYS_ORDER = ['L','M','X','J','V','S','D'];
export const DAY_NAMES = {L:'Lunes',M:'Martes',X:'Miércoles',J:'Jueves',V:'Viernes',S:'Sábado',D:'Domingo'};

export const DATA = {
  L:{meals:[
    {slot:'Desayuno',time:'08:00',dish:'Yogur y fruta · Leche con cacao',
     prep:[{who:'maria',t:'Mezcla el yogur griego con la chía, la crema de cacahuete, los arándanos y el kiwi.'},
           {who:'carlos',t:'Calienta la leche y disuelve el cacao puro.'}],
     items:[{n:'Creatina',m:5,c:5},{n:'Bebida de soja 0%',m:150,c:0,u:'ml'},{n:'Yogur griego 0%',m:125,c:0},
       {n:'Chía',m:5,c:0},{n:'Crema de cacahuete',m:20,c:0},{n:'Arándanos',m:30,c:0},{n:'Kiwi',m:70,c:0},
       {n:'Leche semidesnatada',m:0,c:250,u:'ml'},{n:'Cacao puro 0%',m:0,c:8}]},
    {slot:'Media mañana',time:'',dish:'Tortitas y embutido',
     items:[{n:'Tortitas de maíz',m:0,c:30},{n:'Lomo embuchado',m:0,c:60}]},
    {slot:'Comida',time:'14:00',dish:'Plato libre',
     items:[{n:'Verdura a elegir',m:200,c:200},{n:'Proteína no grasa',m:170,c:170},{n:'Carbohidrato a elegir',m:50,c:50},
       {n:'Fruta',m:160,c:160,note:'Marcado «NO POSTRE» — confirmar si se toma'}]},
    {slot:'Pre-entreno',time:'',dish:'',
     items:[{n:'Plátano',m:160,c:160,note:'Solo si entrenáis'},{n:'Tortitas de maíz',m:15,c:0},{n:'Lomo embuchado',m:30,c:0}]},
    {slot:'Cena',time:'21:00',dish:'Salmón con boniato y gazpacho',
     items:[{n:'Gazpacho',m:200,c:200,u:'ml'},{n:'Aceite de oliva',m:5,c:5,u:'ml'},{n:'Boniato',m:180,c:180},
       {n:'Salmón',m:170,c:200},{n:'Fresas',m:150,c:150},{n:'Yogur griego 0%',m:125,c:125}]},
  ]},
  M:{meals:[
    {slot:'Desayuno',time:'08:00',dish:'Porridge de avena · Leche con cacao',
     prep:[{who:'maria',t:'Mezcla los copos de avena con la leche desnatada y calienta 2-3 min. Corona con las fresas y la crema de cacahuete.'},
           {who:'carlos',t:'Calienta la leche y disuelve el cacao puro.'}],
     items:[{n:'Copos de avena',m:25,c:0},{n:'Leche desnatada',m:200,c:0,u:'ml'},{n:'Fresas',m:100,c:0},
       {n:'Creatina',m:5,c:5},{n:'Bebida de soja 0%',m:150,c:0,u:'ml'},{n:'Crema de cacahuete',m:20,c:0},
       {n:'Leche semidesnatada',m:0,c:250,u:'ml'},{n:'Cacao puro 0%',m:0,c:8}]},
    {slot:'Media mañana',time:'',dish:'Anacardos y pavo',
     items:[{n:'Anacardos',m:0,c:30},{n:'Pechuga de pavo 92%',m:0,c:50}]},
    {slot:'Comida',time:'14:00',dish:'Poke bowl de pollo',
     prep:[{who:'ambos',t:'Cuece el arroz y déjalo templar. Cocina el pollo troceado. Monta el bowl con el aguacate, el maíz, el edamame, el tomate cherry y el pepino; remata con las pipas.'}],
     items:[{n:'Arroz',m:60,c:60},{n:'Pechuga de pollo',m:170,c:170},{n:'Aguacate',m:100,c:100},{n:'Maíz',m:30,c:30},
       {n:'Edamame',m:50,c:50},{n:'Tomate cherry',m:100,c:100},{n:'Pepino',m:100,c:100},{n:'Pipas de calabaza',m:10,c:10}]},
    {slot:'Pre-entreno',time:'',dish:'',
     items:[{n:'Plátano',m:160,c:160,note:'Solo si entrenáis'},{n:'Yogur de proteínas',m:120,c:0},{n:'Chocolate negro 85%',m:8,c:0}]},
    {slot:'Cena',time:'21:00',dish:'Ensalada de atún, mango y feta',
     prep:[{who:'ambos',t:'Escurre el atún. Trocea el mango, el aguacate y el pepino. Mézclalo con la espinaca, el tomate cherry, el pepinillo y el feta.'},
           {who:'carlos',t:'Añade las lentejas escurridas.'}],
     items:[{n:'Atún claro al natural (Dia)',m:120,c:120},{n:'Mango',m:100,c:100},{n:'Queso feta',m:30,c:30},
       {n:'Pepinillo en vinagre',m:50,c:50},{n:'Aguacate',m:50,c:50},{n:'Espinaca',m:30,c:30},
       {n:'Tomate cherry',m:150,c:150},{n:'Pepino',m:100,c:100},{n:'Lentejas cocidas en bote',m:0,c:150}]},
  ]},
  X:{meals:[
    {slot:'Desayuno',time:'08:00',dish:'Yogur y fruta · Leche con cacao',
     prep:[{who:'maria',t:'Mezcla el yogur griego con la chía, la crema de cacahuete, los arándanos y el kiwi.'},
           {who:'carlos',t:'Calienta la leche y disuelve el cacao puro.'}],
     items:[{n:'Creatina',m:5,c:5},{n:'Bebida de soja 0%',m:150,c:0,u:'ml'},{n:'Yogur griego 0%',m:125,c:0},
       {n:'Chía',m:5,c:0},{n:'Crema de cacahuete',m:20,c:0},{n:'Arándanos',m:30,c:0},{n:'Kiwi',m:70,c:0},
       {n:'Leche semidesnatada',m:0,c:250,u:'ml'},{n:'Cacao puro 0%',m:0,c:8}]},
    {slot:'Media mañana',time:'',dish:'Tortitas y embutido',
     items:[{n:'Tortitas de maíz',m:0,c:30},{n:'Lomo embuchado',m:0,c:60}]},
    {slot:'Comida',time:'14:00',dish:'Ensalada de edamame, garbanzos y pavo',
     prep:[{who:'ambos',t:'Cocina la pechuga de pavo y trocéala. Mezcla la espinaca, el edamame, los garbanzos, el feta y el aguacate; añade el pavo y la manzana en dados.'}],
     items:[{n:'Espinaca',m:30,c:30},{n:'Edamame',m:40,c:40},{n:'Garbanzos cocidos',m:150,c:150},{n:'Queso feta',m:20,c:20},{n:'Aguacate',m:50,c:50},
       {n:'Pechuga de pavo',m:170,c:200},{n:'Manzana',m:90,c:90,note:'En vez de la granada'},{n:'Nueces',m:0,c:15}]},
    {slot:'Pre-entreno',time:'',dish:'',
     items:[{n:'Plátano',m:160,c:160,note:'Solo si entrenáis'},{n:'Tortitas de maíz',m:15,c:0},
       {n:'Lomo embuchado',m:30,c:0},{n:'Mandarina',m:70,c:0}]},
    {slot:'Cena',time:'21:00',dish:'Revuelto de setas con huevo y atún',
     prep:[{who:'ambos',t:'Saltea las setas, el champiñón y el calabacín con el aceite; cuaja el huevo. Acompaña con el atún escurrido y las patatas. De postre, fresas.'}],
     items:[{n:'Setas',m:50,c:50},{n:'Champiñón',m:50,c:50},{n:'Calabacín',m:100,c:100},{n:'Aceite de oliva',m:9,c:9,u:'ml'},
       {n:'Huevo',m:100,c:100},{n:'Atún claro al natural (Carrefour)',m:50,c:50},{n:'Patatas',m:160,c:160},{n:'Fresas',m:150,c:150}]},
  ]},
  J:{meals:[
    {slot:'Desayuno',time:'08:00',dish:'Porridge de avena · Leche con cacao',
     prep:[{who:'maria',t:'Mezcla los copos de avena con la leche desnatada y calienta 2-3 min. Corona con las fresas y la crema de cacahuete.'},
           {who:'carlos',t:'Calienta la leche y disuelve el cacao puro.'}],
     items:[{n:'Copos de avena',m:25,c:0},{n:'Leche desnatada',m:200,c:0,u:'ml'},{n:'Fresas',m:100,c:0},
       {n:'Creatina',m:5,c:5},{n:'Bebida de soja 0%',m:150,c:0,u:'ml'},{n:'Crema de cacahuete',m:20,c:0},
       {n:'Leche semidesnatada',m:0,c:250,u:'ml'},{n:'Cacao puro 0%',m:0,c:8}]},
    {slot:'Media mañana',time:'',dish:'Anacardos y pavo',
     items:[{n:'Anacardos',m:0,c:30},{n:'Pechuga de pavo 92%',m:0,c:50}]},
    {slot:'Comida',time:'14:00',dish:'Ensalada de cherrys y burrata con pavo',
     prep:[{who:'ambos',t:'Cocina la pechuga de pavo a la plancha y trocéala. Monta la ensalada con el tomate cherry, la burrata y la espinaca; aliña con el aceite.'},
           {who:'carlos',t:'Acompaña con el arroz cocido.'}],
     items:[{n:'Tomate cherry',m:150,c:150},{n:'Queso burrata',m:60,c:60},{n:'Espinaca',m:30,c:30},
       {n:'Pechuga de pavo',m:150,c:200},{n:'Aceite de oliva',m:5,c:5,u:'ml'},{n:'Arroz',m:0,c:60}]},
    {slot:'Pre-entreno',time:'',dish:'',
     items:[{n:'Plátano',m:160,c:160,note:'Solo si entrenáis'},{n:'Yogur de proteínas',m:120,c:0},{n:'Chocolate negro 85%',m:8,c:0}]},
    {slot:'Cena',time:'21:00',dish:'Tartar de salmón',
     prep:[{who:'ambos',t:'Pica el salmón y la cebolla. Adereza con la salsa de soja, la mostaza, el limón y el orégano. Sirve con el aguacate. De postre, nísperos y yogur.'}],
     items:[{n:'Salmón',m:170,c:170},{n:'Aguacate',m:60,c:60},{n:'Cebolla',m:30,c:30},{n:'Limón',m:20,c:20},
       {n:'Salsa de soja',m:20,c:20,u:'ml'},{n:'Mostaza de Dijon',m:10,c:10},{n:'Orégano',m:3,c:3},
       {n:'Nísperos',m:140,c:140},{n:'Yogur griego 0%',m:125,c:125}]},
  ]},
  V:{meals:[
    {slot:'Desayuno',time:'08:00',dish:'Yogur y fruta · Leche con cacao',
     prep:[{who:'maria',t:'Mezcla el yogur griego con la chía, la crema de cacahuete, los arándanos y el kiwi.'},
           {who:'carlos',t:'Calienta la leche y disuelve el cacao puro.'}],
     items:[{n:'Creatina',m:5,c:5},{n:'Bebida de soja 0%',m:150,c:0,u:'ml'},{n:'Yogur griego 0%',m:125,c:0},
       {n:'Chía',m:5,c:0},{n:'Crema de cacahuete',m:20,c:0},{n:'Arándanos',m:30,c:0},{n:'Kiwi',m:70,c:0},
       {n:'Leche semidesnatada',m:0,c:250,u:'ml'},{n:'Cacao puro 0%',m:0,c:8}]},
    {slot:'Media mañana',time:'',dish:'Tortitas y embutido',
     items:[{n:'Tortitas de maíz',m:15,c:30},{n:'Lomo embuchado',m:30,c:60}]},
    {slot:'Comida',time:'14:00',dish:'Pita de pollo con salsa de yogur',
     prep:[{who:'ambos',t:'Rellena el pan de pita con el pollo cocinado, la lechuga, la cebolla y el tomate. Aliña con la salsa de yogur (yogur y limón). Acompaña con las patatas; uvas de postre.'},
           {who:'carlos',t:'Añade el aguacate y el queso en lonchas.'}],
     items:[{n:'Pan de pita',m:134,c:134},{n:'Contramuslo de pollo',m:150,c:150},{n:'Lechuga',m:30,c:30},
       {n:'Cebolla',m:30,c:30},{n:'Tomate',m:50,c:50},{n:'Yogur griego 0%',m:125,c:125},{n:'Limón',m:50,c:50},
       {n:'Aguacate',m:0,c:60},{n:'Queso en lonchas light',m:0,c:25},{n:'Patatas',m:160,c:160},{n:'Uvas',m:150,c:150}]},
    {slot:'Cena',time:'21:00',dish:'Pizza casera',
     prep:[{who:'ambos',t:'Cubre la base con el tomate triturado, la mozzarella, el jamón cocido, la cebolla y el champiñón. Hornea hasta que funda. Uvas de postre.'}],
     items:[{n:'Base de pizza',m:140,c:140},{n:'Tomate triturado',m:100,c:100,u:'ml'},{n:'Queso mozzarella',m:100,c:120},
       {n:'Jamón cocido',m:60,c:60},{n:'Cebolla',m:30,c:30},{n:'Champiñón',m:30,c:30},{n:'Uvas',m:200,c:200}]},
  ]},
  S:{meals:[
    {slot:'Desayuno',time:'09:00',dish:'Tortitas de avena con sirope',
     prep:[{who:'ambos',t:'Bate los copos con el huevo y la leche; haz las tortitas en la sartén. Derrite el chocolate con la leche semi para el sirope. Acompaña con arándanos.'}],
     items:[{n:'Copos de avena',m:50,c:50},{n:'Huevo',m:50,c:50},{n:'Leche desnatada',m:100,c:100,u:'ml'},
       {n:'Chocolate negro 85%',m:16,c:16},{n:'Leche semidesnatada',m:10,c:260,u:'ml'},{n:'Arándanos',m:50,c:50},
       {n:'Bebida de soja 0%',m:150,c:0,u:'ml'},{n:'Cacao puro 0%',m:0,c:8}]},
    {slot:'Comida',time:'14:00',dish:'Hamburguesa de ternera',
     prep:[{who:'ambos',t:'Mezcla la carne con el ajo y el perejil; forma la hamburguesa y hazla a la plancha. Monta con el pan, el huevo a la plancha y el queso.'}],
     items:[{n:'Filete de ternera',m:175,c:175},{n:'Ajo',m:5,c:5},{n:'Perejil',m:5,c:5},
       {n:'Pan de hamburguesa',m:75,c:75,note:'De panadería'},{n:'Huevo',m:50,c:50},{n:'Queso en lonchas light',m:25,c:0}]},
    {slot:'Cena',time:'',free:'Sin cena pautada en el plan.'},
  ]},
  D:{meals:[
    {slot:'Desayuno',time:'09:00',dish:'Tostada de pan integral con jamón y huevo',
     prep:[{who:'ambos',t:'Tuesta el pan integral. Acompaña con el jamón curado, el huevo y el tomate; un hilo de aceite.'},
           {who:'carlos',t:'Con leche y cacao.'}],
     items:[{n:'Pan integral',m:60,c:60},{n:'Jamón curado/serrano',m:40,c:50},{n:'Huevo',m:50,c:50},
       {n:'Tomate',m:70,c:70},{n:'Aceite de oliva',m:5,c:5,u:'ml'},{n:'Bebida de soja 0%',m:150,c:0,u:'ml'},
       {n:'Leche semidesnatada',m:0,c:250,u:'ml'},{n:'Cacao puro 0%',m:0,c:8}]},
    {slot:'Comida',time:'14:00',dish:'Ensalada de sardinas y cottage',
     prep:[{who:'ambos',t:'Mezcla las sardinas con el cottage, los pimientos, el tomate y el maíz. Añade las nueces. Acompaña con las patatas.'}],
     items:[{n:'Sardina',m:90,c:90},{n:'Queso cottage',m:100,c:100},{n:'Pimiento rojo',m:50,c:50},
       {n:'Tomate',m:70,c:70},{n:'Pimiento verde',m:50,c:50},{n:'Maíz',m:30,c:30},{n:'Patatas',m:250,c:250},{n:'Nueces',m:20,c:20}]},
    {slot:'Cena',time:'20:00',dish:'Ensalada crunchy de pasta de lentejas',
     prep:[{who:'ambos',t:'Cuece la pasta de lentejas. Mézclala con el pollo cocinado, el huevo, el tomate cherry y las pipas; aliña con el aceite y la mostaza.'}],
     items:[{n:'Pasta de lentejas',m:50,c:50},{n:'Pechuga de pollo',m:130,c:130},{n:'Huevo',m:50,c:50},
       {n:'Pipas de calabaza',m:10,c:10},{n:'Tomate cherry',m:100,c:100},{n:'Aceite de oliva',m:5,c:5,u:'ml'},{n:'Mostaza de Dijon',m:5,c:5}]},
  ]},
};
